### ISSUE TITLE
Getting a 'translations' relationship missing error

### ISSUE THREAD

**Issue by anthony-brindley** [MonstreX/voyager-site#20]
Hi, I stumbled across this system a couple of days ago and have been experimenting with it ever since and I'm very impressed! Thank you. 

The only major problem that I've come across is that I keep running into this error about a relationship between a page and translations. 
Error screenshot: https://www.dropbox.com/s/mu6xh1tyk3pxeaj/chrome_2022-03-11_15-44-26.png?dl=0 

I've checked the file vendor/monstrex/voyager-site/src/Models/Page and there is indeed no relationship specified. I am probably doing something wrong but I'm not sure why this would be the case? 

For reference, I have basically copied the PageController setup that you specified in the documentation but I've got the homepage working by managing to extend the base TCG Page model and adding in the missing relationship. All the files are below: 

-- PageController.php
``
<?php

namespace App\Http\Controllers;

use MonstreX\VoyagerSite\Traits\PageTrait;

class PageController extends Controller
{
    use PageTrait;

    public function home()
    {

        $this->create('home', 'page'); //<-- I added this page slug to reference my Extended page model rather than using the default

        return $this->view();

    }

    public function show($alias)
   {
        $this->create($alias); //<!-- this one is default and gives the error as per the screenshot

        return $this->view();

    }

//    public function showArticle($alias)
//    {
//
//        $this->create($alias,'articles');
//
//        return $this->view('layout.article', ['vars' => $some_vars]);
//
//    }

}``

-- Routes/web.php

``
Route::get('/', [PageController::class, 'home'])->name('home');

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

Route::get('/{any}', [PageController::class, 'show']);
``

--App\Models\Page.php

``
namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use MonstreX\VoyagerSite\Models\Page as MonstreXPage;
use TCG\Voyager\Models\Translation;

class Page extends MonstreXPage
{
    use HasFactory;

    public function translations()
    {
        return $this->hasMany(Translation::class, 'foreign_key');
    }
}
``

Any help would be appreciated? 

Thanks

Anthony

**Comment by MonstreX** [comment]
Thank you for your report! Yep, you're right. It's my fault. Will be fixed on the next release. Anyway, you can fix it temporarily right now in the file /src/Services/VoyagerData.php (38):
Comment this line: $data = $model::with('translations')->where($field, $value)->first();
Or replace this line with:
```php
if (Voyager::translatable($model)) {
    $data = $model::with('translations')->where($field, $value)->first();
} else {
    $data = $model::where($field, $value)->first();
}
```
It should resolve the issue.
