### ISSUE TITLE
Adding additional fields to blocks

### ISSUE THREAD

**Issue by eddielee394** [MonstreX/voyager-site#5]
What would be the recommended approach to adding & rendering additional block fields?  For example, if i wanted to add an additional field called `meta` to the `blocks` table.  Then in my view retrieve and display the `meta` field for a given block.

**Comment by MonstreX** [comment]
Initially, each block used only render function that renders the block using an internal template (based on the liquid engine). Inside this template, you can use the attached media files and/or additional "data sources" (such as records of necessary tables).
Any extra data have to be stored in the Options (Parameters) field using JSON format. But I think it would be useful to get this data from the built-in template as of from outside using the blade view template. And the same way I plan to implement for additional fields in the block table as you mentioned above.
